### ISSUE TITLE
Criar Orçamento - Tela inicial

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#1]
Temos que melhorar a comunicação na tela inicial do criar orçamento alterando a frase "Adicione produtos ao seu orçamento" por "Crie a sua lista de compras adicionando os produtos através do botão +"

![image](https://cloud.githubusercontent.com/assets/20990100/18479179/6a8064f4-79aa-11e6-8bf5-0e6105dcfc22.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido
