### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#10]
é fácil criar um widgets Pra Construir?
![screenshot_2016-09-17-16-33-48](https://cloud.githubusercontent.com/assets/20990100/18618117/1db31562-7db6-11e6-8073-c5656313a388.png)
![screenshot_2016-09-17-16-33-57](https://cloud.githubusercontent.com/assets/20990100/18618118/1db408c8-7db6-11e6-8ec0-5be448f1754f.png)
![screenshot_2016-09-17-16-34-07](https://cloud.githubusercontent.com/assets/20990100/18618119/1db7459c-7db6-11e6-8022-a4bb3b665664.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo fácil é muito relativo hehe. Pode ser planejado e especificado esse widget, definindo o escopo dele (por exemplo apenas listar orçamentos e pedidos, com o status e informações relevantes).
