### ISSUE TITLE
Meu Resumo - Não deveria exibir a data de criação e telefone

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#107]
Não me lembro de exibirmos a data de criação e o número do telefone no Android
![arquivo_004](https://cloud.githubusercontent.com/assets/20990100/25879505/60c0e3ca-3508-11e7-9785-9d904c14daba.png)
![arquivo_005](https://cloud.githubusercontent.com/assets/20990100/25879507/69d99600-3508-11e7-91be-a98623d93f30.png)

**Comment by lucasretondo** [comment]
Continua exibindo...
![img_1464](https://cloud.githubusercontent.com/assets/20990100/26215697/bffcb8ac-3bd7-11e7-8cbb-d18bc1bd6d55.PNG)
![img_1475](https://cloud.githubusercontent.com/assets/20990100/26215702/c2eaff88-3bd7-11e7-84b4-b4fce18a7939.PNG)

**Comment by claudineicaetano** [comment]
@lucasretondo aqui está OK na versão 2.1.20 de sexta-feira.

![telefonedatacriacao](https://cloud.githubusercontent.com/assets/22913165/26420691/b72837e4-4099-11e7-8a1d-3d79e29ea8aa.jpg)
