### ISSUE TITLE
Não consigo entrar pelo Facebook

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#11]
Não entra pelo Facebook
![image](https://cloud.githubusercontent.com/assets/20990100/18618481/17a28e48-7dbe-11e6-880b-156de6f42342.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18618482/1967dab2-7dbe-11e6-863f-ec7e3419e48f.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18618483/1ba44860-7dbe-11e6-8653-4dcbc8370437.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo por favor forneça maiores detalhes, repita esses passos e me informe os dados utilizados (conta de e-mail do Facebook por exemplo)
