### ISSUE TITLE
Meus Pedidos - As mensagem sumiram depois de responder

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#111]
Depois que respondi uma mensagem com sucesso as mensagens sumiram.

![arquivo_003](https://cloud.githubusercontent.com/assets/20990100/25879638/2441dc50-3509-11e7-8a9f-8f9546716f2e.png)

**Comment by claudineicaetano** [comment]
@lucasretondo qual foi o fluxo executado? Será que o problema foi aqui na mensageria? Fiz o seguinte fluxo:
Como cliente criei um orçamento / como lojista fiz uma pergunta/ Como Cliente respondi a pergunta / Como lojista dei ciência da resposta do cliente. Em todos os pontos funcionou como esperado. Inclusive durante o processo saí e entrei novamente no app para ver se estava. Veja os prints. Obs. É possível que o problema possa ser em outro ponto e não propriamente no sistema de mensageria. Confirme este teste.

![image uploaded from ios](https://cloud.githubusercontent.com/assets/22913165/26421328/15ce2d60-409c-11e7-81d9-72b12497ec76.jpg)

![image uploaded from ios 3](https://cloud.githubusercontent.com/assets/22913165/26421369/37f41e5e-409c-11e7-96e4-a4c3a82a6ed6.jpg)

![image uploaded from ios 2](https://cloud.githubusercontent.com/assets/22913165/26421418/6266baac-409c-11e7-8258-3bc32f3f87c9.jpg)


![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/22913165/26421428/68dbdea8-409c-11e7-9fe7-cd1d9212829d.jpg)

**Comment by lucasretondo** [comment]
@claudineicaetano vou tentar novamente neste última versão, mas eu segui o mesmo fluxo.
