### ISSUE TITLE
Meus Pedidos - Melhorar o layout da caixa de mensagem e justificativa das avaliações

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#113]
Temos muito espaço nas telas de mensagens, não faz sentido deixarmos uma fonte tão pequena tão próxima do menu superior, precisamos melhorar este layout.

![arquivo_001](https://cloud.githubusercontent.com/assets/20990100/25879714/91d04d24-3509-11e7-84bd-0f7636919e3d.png)

![arquivo_002](https://cloud.githubusercontent.com/assets/20990100/25879715/9386693c-3509-11e7-82e7-0f4201561635.png)

**Comment by lucasretondo** [comment]
Mudar de observação para mensagem
![img_1478](https://cloud.githubusercontent.com/assets/20990100/26215732/ddf40b3a-3bd7-11e7-921f-8d98bd13f168.PNG)

**Comment by claudineicaetano** [comment]
Alteração no layout, não se aplica mais no fluxo.

**Comment by raphaelMCarvalho** [comment]
Fechando já que não se aplica mais ao layout atual.
