### ISSUE TITLE
Meus Pedidos - Unificar pedido e entrega

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#116]
Não faz sentido exibirmos dois campos com o mesmo símbolo, vamos unificar a data da entrega e o período em uma única linha?
![arquivo_005 1](https://cloud.githubusercontent.com/assets/20990100/26134531/b830550a-3a85-11e7-967d-c5cdedac76cd.png)

**Comment by lucasretondo** [comment]
Nos Meus Pedidos foi feito, mas esquecemos do Meus Orçamentos, temos que fazer a mesma coisa.
![img_1462](https://cloud.githubusercontent.com/assets/20990100/26215542/165a30c2-3bd7-11e7-8604-f71a2fc6b44e.PNG)

**Comment by claudineicaetano** [comment]
@lucasretondo Está issue aqui é a mesma que a 159. Precisa fechar.

**Comment by raphaelMCarvalho** [comment]
@claudineicaetano Vamos fechar a #159 que é a mais recente e portanto duplicada

**Comment by raphaelMCarvalho** [comment]
Android, disponível no Beta 1.1.17
