### ISSUE TITLE
Criar Pedido - Mudar o nome do otimizador

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#124]
Mudar o nome do otimizador de "Menor qtd. de fornecedores" para "Menos lojas"
![img_1391](https://cloud.githubusercontent.com/assets/20990100/26192143/ec6562be-3b86-11e7-9753-5480a25de398.PNG)

Exibir sempre na ordem Menor Custos > Melhor Avaliação > Menos lojas.

Não entendi a opção "Nenhuma"?

**Comment by claudineicaetano** [comment]
Esta opção é quando não há nenhuma otimização. Apenas para evidenciar ao usuário. Acha que é melhor tirar?
