### ISSUE TITLE
Criar Orçamento - Exibe datas inválidas

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#131]
Na hora do usuário selecionar a data de entrega o app permite que ele escolha datas inválidas (no exemplo abaixo 17 e 18) para alertá-lo somente após ter selecionado.

![img_1387](https://cloud.githubusercontent.com/assets/20990100/26192742/3d299fd8-3b89-11e7-90ee-60d8fed62090.PNG)
![img_1388](https://cloud.githubusercontent.com/assets/20990100/26192741/3d287ea0-3b89-11e7-8088-0cd869d77f09.PNG)

Não é melhor exibir estas datas em cinza e não permitir que o usuário selecione estas datas?

**Comment by raphaelMCarvalho** [comment]
Disponível no Android na versão Beta 1.1.16
