### ISSUE TITLE
Meus Pedidos - Fica parado na mesmo tela

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#132]
Quando o usuário finaliza a confirmação da entrega ou faz a avaliação fica preso na mesmo tela, quando o ideal é ele volta para a tela Meus Pedidos

**Comment by lucasretondo** [comment]
Continua ficando parada na mesma tela após confirmar entrega ou fazer a avaliação com o pedido detalhado.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A ser disponibilizado em atualização no TestFlight ainda hoje
