### ISSUE TITLE
Meus Orçamentos - Padronizar posição do botão CANCELAR

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#149]
Tenho a impressão que o botão CANCELAR na outras telas aparece mais próximo ao canto do quadro.
![img_1463](https://cloud.githubusercontent.com/assets/20990100/26216793/bacc21ac-3bdb-11e7-81ab-e7f0a058bbed.PNG)

**Comment by claudineicaetano** [comment]
Lucas, o alinhamento é sempre à direita, ou seja, um botão é alinhando com relação ao outro. Então se a palavra Continuar for outra, tudo será reposicionado. Este é um comportamento padrão. Tem como. você enviar as telas que estão incoerentes.

**Comment by lucasretondo** [comment]
Neste exemplo o botão CANCELAR esta no canto esquerdo. Acho este layout mais agradável.
![image](https://user-images.githubusercontent.com/20990100/28477559-ee83fa84-6e2a-11e7-8447-c77d11bfa124.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível daqui a pouco no Testflight na versão 2.2.26
