### ISSUE TITLE
Meus Pedidos - Mudar o título da tela de observação para mensagem

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#150]
![img_1471](https://cloud.githubusercontent.com/assets/20990100/26216921/2e6e01ac-3bdc-11e7-8b0d-a9057d0ae4af.PNG)

**Comment by claudineicaetano** [comment]
@lucasretondo Não encontrei esta tela. Tem certeza que é em Meus Pedidos?

**Comment by lucasretondo** [comment]
@claudineicaetano esta tela aparece quando o usuário vai responder uma mensagem enviado pelo lojista, achou?
