### ISSUE TITLE
Incluir fotos no app

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#153]
Hoje quando o usuário abre o app pela primeira vez é direcionado direto para a tela de login, sem nenhuma explicação.

Precisamos melhorar a nossa comunicação incluindo algumas fotos com os benefícios de usar o app.

As fotos e textos já foram enviado ao Claudinei.

**Comment by raphaelMCarvalho** [comment]
Testar Android, na versão 1.1.15
