### ISSUE TITLE
Criar Orçamento - O logo esta apagado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#154]
O que aconteceu com o logo?
![screenshot_2017-05-21-10-29-20](https://cloud.githubusercontent.com/assets/20990100/26286840/c8b1edcc-3e44-11e7-9ee0-9a69b360c13b.png)
![image](https://cloud.githubusercontent.com/assets/20990100/26286834/b920c5f4-3e44-11e7-88db-d4c805ebade8.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Nos meus devices não está ocorrendo esse problema, deve ser algo específico pra alguma dimensão de tela. Qual o seu dispositivo pra eu tentar recriar as condições?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Qual seu dispositivo Android e versão do sistema?

**Comment by lucasretondo** [comment]
![whatsapp image 2017-05-26 at 15 47 24](https://cloud.githubusercontent.com/assets/20990100/26508324/ba828e0c-422a-11e7-82f6-24baae6c14a5.jpeg)

**Comment by raphaelMCarvalho** [comment]
Android, disponível no Beta 1.1.17

**Comment by lucasretondo** [comment]
@raphaelMCarvalho infelizmente continua apagado.

![screenshot_2017-05-27-21-01-18](https://cloud.githubusercontent.com/assets/20990100/26525119/7b4eb45a-4323-11e7-88da-bf1f5c2dd339.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Esse problema parece afetar algumas resoluções de tela. Nesse exemplo e no meu celular está aparecendo sem problemas. Vou continuar investigando.

![screenshot_1496091494](https://cloud.githubusercontent.com/assets/20994342/26562728/5c2ae2d8-449f-11e7-8713-a6ffe11e77de.png)

**Comment by lucasretondo** [comment]
Mistérios da informática... hhahaha
