### ISSUE TITLE
Meus Orçamentos - Não esta carregando os meus orçamentos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#155]
Exemplo usuário: cli1@mailinator.com (senha cli1$$)
![screenshot_2017-05-21-10-37-49](https://cloud.githubusercontent.com/assets/20990100/26286851/f3467e22-3e44-11e7-9fb8-e93002519def.png)
![image](https://cloud.githubusercontent.com/assets/20990100/26286868/3bfc5790-3e45-11e7-9cbd-48bf631b2256.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já identifiquei o problema, ele está relacionado à quantidade de orçamentos do usuário e o tempo de espera até obter o resultado do webservice e tratar ele para exibir na tela. Chega um momento em que ele dá timeout. Já tenho uma solução em mente pra otimizar esse processo.

**Comment by raphaelMCarvalho** [comment]
Disponível no Android na versão Beta 1.1.16
