### ISSUE TITLE
Cadastro - Não esta exibindo o termo de uso

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#157]
![screenshot_2017-05-21-10-51-17](https://cloud.githubusercontent.com/assets/20990100/26287005/4b56a8d2-3e48-11e7-8630-5a4fcc3254d8.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Correção disponível na versão Beta 1.1.14 que logo deve aparecer na loja

![captura de tela de 2017-05-21 20-25-23](https://cloud.githubusercontent.com/assets/20994342/26288223/a8527d34-3e63-11e7-9b69-6260ecd3e25f.png)
