### ISSUE TITLE
Criar Pedido - O usuário não escolhe a bandeira do cartão

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#158]
Na hora de criar o pedido o usuário não escolhe a bandeira do cartão de crédito ou débito.
![screenshot_2017-05-21-19-39-51](https://cloud.githubusercontent.com/assets/20990100/26299563/9c554072-3eb1-11e7-8c21-27a2200e06c4.png)

**Comment by raphaelMCarvalho** [comment]
Disponível para atualização na versão Beta 1.1.15
