### ISSUE TITLE
Meus Orçamentos - Unificar os campos data e período de entrega

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#159]
Assim como fizemos no iOS, podemos melhorar o layout do Meus Orçamentos e Meus Pedidos unificando as campos data e período de entrega.
![screenshot_2017-05-21-19-43-38](https://cloud.githubusercontent.com/assets/20990100/26299610/c6ee8cb2-3eb1-11e7-8fa2-241a8dfb9ad3.png)

**Comment by raphaelMCarvalho** [comment]
Label Android adicionada à issue já existente: #116

**Comment by raphaelMCarvalho** [comment]
Fechando a issue, usaremos a #116
