### ISSUE TITLE
Não esta enviando o push notification

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#160]
O app não esta alertando o usuário com notificações ao receber uma nova resposta do orçamento ou confirmações do pedido.

**Comment by raphaelMCarvalho** [comment]
Disponível no Beta 1.1.20

**Comment by lucasretondo** [comment]
@raphaelMCarvalho desculpe, fechei sem querer. Não esta enviando a notificação após o lojista confirmar a entrega.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Olhei no webservice, nunca enviou após confirmação de entrega.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Blz, vou colocar na lista de melhorias futuras... era para enviar...

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Beleza, daí se quiser pode reabrir essa issue futuramente pra ter o histórico
