### ISSUE TITLE
Tutorial - Alterar as frases

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#161]
Faltou alterar as frases (doc anexo) conforme e-mail enviado ao Claudinei no dia 19/mai
![image](https://cloud.githubusercontent.com/assets/20990100/26477476/5547cc84-419c-11e7-9bcc-57221ab87de4.png)

[Textos Fotos.docx](https://github.com/PraConstruir/customer_mobile_app/files/1030594/Textos.Fotos.docx)

**Comment by raphaelMCarvalho** [comment]
Disponível no Android na versão Beta 1.1.16

**Comment by lucasretondo** [comment]
@raphaelMCarvalho 

Rapha, acho que as frases não ficaram boas, hoje esta assim:

Bem-vindo!
Estamos aqui para ajudá-lo a comprar os materiais para a sua construção ou reforma.
Prático!
Solicite os orçamentos para as melhores lojas de materiais de construção da sua região com um clique.
Rápido!
Compare os orçamentos de diversas lojas e economize tempo e dinheiro na criação dos pedidos.
Seguro!
Você faz o pagamento direto com a loja que você escolheu.

Depois de ler vc não entendeu ainda como funciona. O que vc acha deste texto:

Bem-vindo!
Queremos ajuda-lo a comprar os materiais para a sua construção ou reforma.
Fácil!
Você faz a sua lista de compras, escolhe o local e a data da entrega e solicita o orçamento.
Eficiente!
Nós enviamos o seu orçamento para as melhores lojas de materiais de construção da sua região.
Ágil!
Compare as cotações e crie os pedidos de compra pelo aplicativo, sem sair de casa.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo É um bom desafio chegar a um conjunto de frases ao mesmo tempo descritivas e de simples leitura, acho que você está num bom caminho. Eu dei uma revisada na última e coloquei nas telas, pra você visualizar melhor, veja o que achou.

![screenshot_1496049821](https://cloud.githubusercontent.com/assets/20994342/26544318/c1c86b46-4437-11e7-9132-4b781d420bee.png)
![screenshot_1496049826](https://cloud.githubusercontent.com/assets/20994342/26544319/c1c895c6-4437-11e7-9f93-2ebd2106a597.png)
![screenshot_1496049831](https://cloud.githubusercontent.com/assets/20994342/26544316/c1c54fd8-4437-11e7-8ea1-b7cb802b4079.png)
![screenshot_1496049836](https://cloud.githubusercontent.com/assets/20994342/26544317/c1c6b95e-4437-11e7-834e-edf4b34d18d6.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho eu gostei, vou fazer um teste com algumas pessoas que não participam diretamente do projeto e te retorno com o ok final... obrigado

**Comment by lucasretondo** [comment]
@raphaelMCarvalho teste feito, todos escolheram este novos textos, pode alterar, obrigado.

**Comment by raphaelMCarvalho** [comment]
Disponível no Beta 1.1.20
