### ISSUE TITLE
Cadastro - Criar a senha no app

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#162]
Temos que fazer no Android o mesmo fluxo de cadastro do iOS, onde o usuário cria a senha dentro do próprio app, não precisando ir para o e-mail.

![screenshot_2017-05-27-20-57-07](https://cloud.githubusercontent.com/assets/20990100/26525124/a02bce2a-4323-11e7-9083-f5118ada3509.png)

**Comment by raphaelMCarvalho** [comment]
Disponível no Beta 1.1.20
