### ISSUE TITLE
Criar Orçamento - Mudar nome do campo Descrição

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#163]
O termo descrição confunde o usuário, mas mudar o nome do campo de "Descrição" para "Observações".

![screenshot_2017-05-27-21-01-59](https://cloud.githubusercontent.com/assets/20990100/26525135/d60a025a-4323-11e7-9e53-e7af73c20458.png)

**Comment by raphaelMCarvalho** [comment]
Disponível na versão Beta 1.1.18
