### ISSUE TITLE
Criar Orçamento - Esta faltando a obra, mas sinaliza a data

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#164]
Quando o usuário tenta solicitar um orçamento sem informar a obra o sistema dá a mensagem de erro correta, mas sinaliza o campo data de entrega ao invés de chamar a atenção para o campo obra.

![screenshot_2017-05-27-21-02-16](https://cloud.githubusercontent.com/assets/20990100/26525139/077cf13a-4324-11e7-80d1-8940241507cc.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo No caso, haviam vários erros para validar, e a mensagem exibe o primeiro erro, que é a ausência de obra. Foram sinalizados os outros campos que também tinham erro. Essa tela em específico como o usuário não possuía obra, está sendo exibido o botão grande escrito "Criar nova obra". A sinalização dos campos ocorre em campos de formulário; como não há obra, o seletor de obras não aparece, não sendo possível marcar o campo portanto.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O que pode ser feito é alterar a mensagem nesse caso para "É preciso criar uma nova obra"
