### ISSUE TITLE
Criar Orçamento - Pede para selecionar uma obra quando não existe nenhuma

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#165]
No exemplo abaixo o usuário ainda não cadastrou nenhum obra e o app pede para ele selecionar uma obra, deixando ele confuso.

![screenshot_2017-05-27-21-02-54](https://cloud.githubusercontent.com/assets/20990100/26525146/4c193c54-4324-11e7-80ce-8035c66dc910.png)

É fácil mudar a frase para "Crie uma obra" quando não houver nenhuma obra cadastrada?

**Comment by raphaelMCarvalho** [comment]
Disponível na versão Beta 1.1.18
