### ISSUE TITLE
Criar Orçamento - Mensagem de alerta não desaparece

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#166]
Mesmo depois de ter informado a data de entrega a "!" de alerta continua sendo exibida.

![screenshot_2017-05-27-21-04-12](https://cloud.githubusercontent.com/assets/20990100/26525150/8b56c184-4324-11e7-9752-f35481cb8501.png)

**Comment by raphaelMCarvalho** [comment]
Disponível no Beta 1.1.19
