### ISSUE TITLE
Criar Orçamento - O usuário só consegue ver 4 opções do autocomplete

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#167]
Hoje o usuário consegue ver somente 4 opções de produto do autocomplete, é possível criar uma forma do usuário rolar a lista de produtos para ter mais opções?

![screenshot_2017-05-27-21-08-45](https://cloud.githubusercontent.com/assets/20990100/26525154/c96d5870-4324-11e7-9105-cff273a1b91f.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Isso acontece porque o teclado está aberto. Para ver mais opções no Android, o comum é o usuário tocar no botão back para esconder o teclado e ver mais opções. É comum na experiência de uso no Android a meu ver.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho entendi, fica ruim, mas não tem o que fazer. Vamos pensar nesta possibilidade de rolar as opções na web e apps no futuro.
