### ISSUE TITLE
Criar Orçamento - Não trava tela enquanto envia o orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#168]
O sistema demora alguns segundos para enviar a solicitação do orçamento, enquanto isso ele deixa o usuário na mesma tela e ainda permite que ele altere os dados. Precisamos travar a tela e dar uma mensagem para o usuário enquanto não aparece a mensagem abaixo:

![screenshot_2017-05-27-21-10-20](https://cloud.githubusercontent.com/assets/20990100/26525167/4d22a2f6-4325-11e7-9bba-330144c0f9e5.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Você tem razão, falta feedback, vamos trabalhar nisso.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Vi que o mesmo acontece ao solicitar pedido, vou já ajustar lá também

**Comment by lucasretondo** [comment]
@raphaelMCarvalho bem lembrado...

**Comment by raphaelMCarvalho** [comment]
Disponível no Beta 1.1.19
