### ISSUE TITLE
Criar Pedido - Colocar a opção "à vista" em primeiro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#169]
Colocar a opção "à vista" em primeiro lugar na lista de parcelas.

![screenshot_2017-05-27-21-19-32](https://cloud.githubusercontent.com/assets/20990100/26525172/7a348dc2-4325-11e7-8c96-72addd4cb65e.png)

**Comment by raphaelMCarvalho** [comment]
Disponível na versão Beta 1.1.18
![captura de tela 2017-05-28 14 26 27](https://cloud.githubusercontent.com/assets/20994342/26531184/36ded84e-43ba-11e7-9aab-328e0a15af14.png)
