### ISSUE TITLE
Obrigatoriedade do CPF

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#17]
O CPF não deveria ser obrigatório sobre na hora de enviar o pedido?
![image](https://cloud.githubusercontent.com/assets/20990100/18618699/4eb7a4c8-7dc2-11e6-8e8f-7dce1307ae8e.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não, é obrigatório no cadastro mesmo
