### ISSUE TITLE
Minhas Obras - Endereço cortado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#174]
O endereço esta cortado...

![img_1714](https://cloud.githubusercontent.com/assets/20990100/26529289/b74c42a4-4393-11e7-8637-7fb5df9c7a0f.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Essa lista não tem a intenção de exibir informações completas, especialmente para manter um layout homogêneo, pois os endereços podem variar muito. Para obter todos os detalhes, o usuário toca no item.
