### ISSUE TITLE
Criar Orçamento - Não exibe o endereço completo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#193]
Exibe o nome da rua quebrado.
![img_1563](https://cloud.githubusercontent.com/assets/20990100/26529601/0dfc0206-4399-11e7-8bbb-5ba156371c7d.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O endereço não foi cortado por engano, as reticências são intencionais pra não quebrar o layout. Essa lista é um preview das informações, sempre que o usuário sentir a necessidade de informações completas, ele toca no item. Se fossemos exibir a rua completa nessa lista, não teríamos uma lista homogênea, o layout ficaria ruim.
