### ISSUE TITLE
Não esta enviando o push notification

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#195]
Issue duplicada devido ao milestone diferente.

**Comment by lucasretondo** [comment]
Quando crio um usuário novo o push funciona, porém quando estou com um usuário já existe ele não funciona.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Realizei testes com usuários que já existiam. A questão é que o token não estava sendo armazenado no servidor. Para armazenar, é preciso que você desinstale o app e instale novamente, fazendo login com seu usuário existente. Passe pra mim qual o e-mail se persistir.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Como pode ver, o push não foi enviado pois não há token registrado para esse usuário. Funciona assim: quando há um token novo recebido da Apple pelo dispositivo, o aplicativo guarda localmente e envia uma cópia para o servidor, registrando o token com o usuário atualmente conectado. Se você faz logoff, os dados locais são removidos por questão de segurança. Ao autenticar com outro usuário, a Apple não envia um novo token (já que o anterior ainda está válido), e então não é registrado um token para o novo usuário conectado. Como o app é de utilização individual, está funcionando como esperado.

PS.: ao remover o aplicativo e instalar novamente, geralmente a Apple gera um novo token e envia para o dispositivo.

![captura de tela 2017-07-04 as 09 45 17](https://user-images.githubusercontent.com/20994342/27830622-9d75588a-609d-11e7-852a-2fb7a33bfc25.png)

**Comment by lucasretondo** [comment]
Entendi, vou fechar esta issue então, obrigado.
