### ISSUE TITLE
Criar Orçamento - Aumentar o tamanho do campo quantidade

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#196]
Vamos aumentar um pouco o tamanho do campo quantidade, na tela abaixo este com a maior medida que temos cadastrada e esta sobrando espaço.
![screenshot_2017-06-08-18-22-44](https://user-images.githubusercontent.com/20990100/26957826-cba65cf4-4c9d-11e7-8c8e-acc03b4a8f12.png)

E aqui a quantidade esta cortada com uma medida pequena.
![screenshot_2017-06-08-18-21-18](https://user-images.githubusercontent.com/20990100/26957838-dda65c60-4c9d-11e7-96c3-5a2a7c25ab03.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Foi aumentado um pouco. Não podemos aumentar muito por causa das diversas resoluções de tela, tem que se comportar bem nos outros casos.

![screenshot_1496975198](https://user-images.githubusercontent.com/20994342/26958592-f141b1f8-4ca1-11e7-88c2-dea054ce1fb9.png)

**Comment by lucasretondo** [comment]
Blz.

**Comment by raphaelMCarvalho** [comment]
Disponível na versão Beta 2.0.3
