### ISSUE TITLE
Criar Orçamento - Mudar nome do campo para "Medida*"

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#197]
Mudar o nome do campo DE "Unidade*" PARA "Medida*"
![screenshot_2017-06-08-18-21-18](https://user-images.githubusercontent.com/20990100/26957862-04ec3088-4c9e-11e7-8c55-5ad7325e7ea4.png)

**Comment by raphaelMCarvalho** [comment]
Disponível na versão Beta 2.0.3
