### ISSUE TITLE
Criar Cadastro - Dificuldade para selecionar o dia do nascimento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#198]
O app abre a data de nascimento como se o usuário tivesse 18 anos (seleciona o dia atual), porém quando ele tenta selecionar um dia maior o app não deixa, dando a impressão ao usuário que não é possível selecionar a data.

O usuário tem que alterar o ano para depois selecionar um dia maior que o atual.

![img_2246](https://user-images.githubusercontent.com/20990100/27830940-ffb496e0-609e-11e7-8ff3-30c76a564301.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Este é comportamento padrão do componente de data do iOS.

**Comment by lucasretondo** [comment]
Não podemos colocar como ano 1998 para evitar que o usuário fique sem saber o que fazer?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Podemos sim. É que a regra utilizada é [dia atual - 18 anos], podemos reduzir para 17 anos, no entanto vai ser possível o cadastro de menores de 18 anos. Pode mandar ver?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo PS.: o usuário escolhe o ano, por exemplo 1999 ou 1998

**Comment by lucasretondo** [comment]
Sim, mas até ele descobrir que tem que mudar o ano para conseguir colocar um dia maior já foi embora.





---- On Ter, 04 jul 2017 10:34:08 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo PS.: o usuário escolhe o ano, por exemplo 1999 ou 1998

**Comment by lucasretondo** [comment]
Não tem como criar duas regras, [dia atual - 18 anos] para o cadastro e [dia atual - 19 anos] para a data padrão?



---- On Ter, 04 jul 2017 10:32:14 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Podemos sim. É que a regra utilizada é [dia atual - 18 anos], podemos reduzir para 17 anos, no entanto vai ser possível o cadastro de menores de 18 anos. Pode mandar ver?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Criar essas duas regras complica bastante pro desenvolvimento e a validação. Como eu disse, é um comportamento padrão do componente, sendo assim, o usuário da plataforma iOS já possui o aprendizado de utilizá-lo pois já teve contato com o mesmo em outros aplicativos.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Isso aí ocorre no locale pt-BR, porque aqui no Brasil o formato é dd-MM-yyyy. Em locales como o en-US, o formato é yyyy-MM-dd, sendo assim eles sempre selecionam o ano primeiramente, o que do meu ponto de vista é o formato que faz mais sentido (ano, mês, dia).

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Outra opção possível é permitir que o usuário insira datas inválidas, por exemplo 01-01-2001. E ao clicar pra salvar, ele é avisado de que a data não pode ser utilizada.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível no TestFlight
