### ISSUE TITLE
Cancelar pedido

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#2]
Não consigo cancelar um pedido

![image](https://cloud.githubusercontent.com/assets/20990100/18479248/b814624c-79aa-11e6-8df0-628210bd1190.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18479354/0d513c94-79ab-11e6-9132-d1ccd70694e0.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo você pode tentar novamente e informar se o problema persiste?
