### ISSUE TITLE
Sair do app para criar senha

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#20]
O esquema de enviar o e-mail para depois criar a senha ficou ruim no app, o usuário tem que sair do aplicativo, criar a senha e depois voltar, temos que pensar em criar a senha de outra forma.
![image](https://cloud.githubusercontent.com/assets/20990100/18618714/8c4bfed8-7dc2-11e6-937c-5a4622df2165.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo quando o usuário cria a senha e clica em Ir para home no navegador web, ele é direcionado de volta para o app. Veja se esse comportamento apareceu para você como esperado.
