### ISSUE TITLE
Meu Resumo - Diminuir a distância entre as linhas

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#200]
É possível diminuir a distância entre as linhas do Meu Resumo?

![img_2248](https://user-images.githubusercontent.com/20990100/27831042-43c859c0-609f-11e7-9986-4d6fa1669758.PNG)

**Comment by raphaelMCarvalho** [comment]
O bloco de Meus Pedidos é possível e foi feito, Meus Orçamentos não é possível em decorrência da quantidade de informações (para atender uma solicitação realizada anteriormente, estamos exibindo o endereço quase completo nessa tela de resumo). Esse ajuste estará disponível no TestFlight em atualização ainda a ser lançada.

![img_1405](https://user-images.githubusercontent.com/20994342/28017046-8f011154-654d-11e7-9996-a5d184a96234.PNG)
