### ISSUE TITLE
Criar Pedido - Trocar a frase "Trocar produto" por "Trocar loja"

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#201]
Vamos trocar a frase "Trocar produto" por "Trocar loja"?

![img_2251](https://user-images.githubusercontent.com/20990100/27831066-5d5df7f0-609f-11e7-81db-966f0fbe386f.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível no TestFlight e no Beta Android, versão 2.0.6
