### ISSUE TITLE
Meu Cadastro - Melhorar a frase e substituir o termo site por app

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#204]
Melhorar a frase e substituir o termo site por app quando u usuário quiser Desativar ou Excluir a sua conta.

![img_2247](https://user-images.githubusercontent.com/20990100/27831141-bdf68776-609f-11e7-998e-7173d21164ed.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Está idêntico ao Android. Alterar lá também?

**Comment by lucasretondo** [comment]
Sim, bem lembrado.
