### ISSUE TITLE
Cadastro - Pergunta o número de telefone

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#205]
Temos que realmente perguntar o número de telefone? Não é possível pegar automaticamente?
![screenshot_2017-07-12-10-00-53](https://user-images.githubusercontent.com/20990100/28120061-5a1e3de4-66ed-11e7-9d3c-73e1aee8129a.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Sim, temos que perguntar. Veja o caso de configurar por exemplo o WhatsApp ou Telegram em um smartphone, todos os aplicativos perguntam o número do telefone. Não há uma forma garantida de obter o número de telefone porque o mesmo nem sempre é armazenado no SIM card. Ainda que fizéssemos isso, há o downside de adicionarmos uma nova permissão no aplicativo pra que seja possível ler o número de telefone, algo que contribui para desconfiança do usuário.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho blz, vamos deixar assim, obrigado.
