### ISSUE TITLE
Criar Orçamento - Não permite solicitar um orçamento em Piracicaba

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#206]
Não permite solicitar um orçamento para o endereço abaixo em Piracicaba.
![screenshot_2017-07-12-10-02-19](https://user-images.githubusercontent.com/20990100/28120144-920b4e22-66ed-11e7-9c89-2fdde11991c5.png)
![screenshot_2017-07-12-10-09-39](https://user-images.githubusercontent.com/20990100/28120152-969c9b3a-66ed-11e7-81f4-ce1e221a617f.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Sabe dizer quais foram os produtos solicitados no orçamento e quais as formas de pagamento selecionadas? Haviam lojistas na região que atendiam aos materiais solicitados e também às formas de pagamento? A resposta a essas perguntas é tão importante quanto o endereço, já que são outros pontos de igual peso que podem retornar essa mensagem. Após analisar os dados relativos a essas perguntas, caso haja eventual problema na solicitação de orçamentos, cabe ressaltar que essa mensagem é retornada pela API, não sendo portanto uma issue do aplicativo Android.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Tenho certeza que todas as outras condições foram satisfeitas.

**Comment by raphaelMCarvalho** [comment]
Precisamos dessas informações pra tentar recriar as condições do seu teste: materiais que foram solicitados e formas de pagamento selecionadas pelo cliente. Ao fazer a mesma solicitação usando a versão web, a solicitação teve sucesso naquele momento em que você tentou com o Android?

Enviado do meu iPhone

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Como eu já havia citado, se houvesse um problema na solicitação de orçamento, dada a captura de tela que você anexou, este não seria um problema no aplicativo. Procurando na base de dados por endereços com o CEP informado, vejo que para este endereço, a API do Google não retornou latitude e longitude, que é utilizado para localizar lojistas que atendam à solicitação. Crie essa issue na versão web para investigarmos e tratarmos casos semelhantes.
![captura de tela 2017-07-14 as 08 33 52](https://user-images.githubusercontent.com/20994342/28210740-4b551a8e-686f-11e7-855f-2ab0a624d78a.png)
