### ISSUE TITLE
Push Notification - Não esta agrupando as notificações

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#207]
Ele parou de agrupar as notificações.
![screenshot_2017-07-12-10-07-15](https://user-images.githubusercontent.com/20990100/28120191-ad11ffa4-66ed-11e7-943b-463eff8e8956.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Ajuste será liberado essa tarde em nova atualização da versão Beta

**Comment by lucasretondo** [comment]
@raphaelMCarvalho as primeiras notificações estavam com o ícone, mas quando cheguei no pedido as notificações ficaram sem o ícone e desagrupadas.

![whatsapp image 2017-08-19 at 07 37 56](https://user-images.githubusercontent.com/20990100/29485932-8b93209c-84b1-11e7-829a-69e117036414.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo No Android, só passou a existir uma função nativa para agrupar notificações a partir do Android 7 em smartphones e já havia algo para smart watches, sendo assim, tivemos que desenvolver manualmente essa lógica. A questão é que essa lógica precisa ser aplicada ao receber a notificação, e esse método por padrão só é chamado quando o aplicativo não está em background ou fechado. Ou seja, no método atual, na prática as notificações apenas são agrupadas quando o usuário está com o app aberto. Para permitir que sejam agrupadas a todo momento, mesmo com o app fechado, teremos que refatorar toda esta parte de notificações, provavelmente será necessário também modificar a API, que é a que envia as notificações para os servidores da Google, e o iOS.

**Comment by lucasretondo** [comment]
Esqueci, não precisa desenvolver nada, vamos usar o que é nativo, versões anteriores não precisa agrupar as notificações.



Obrigado



---- On Ter, 17 out 2017 12:16:37 -0200 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo No Android, só passou a existir uma função nativa para agrupar notificações a partir do Android 7 em smartphones e já havia algo para smart watches, sendo assim, tivemos que desenvolver manualmente essa lógica. A questão é que essa lógica precisa ser aplicada ao receber a notificação, e esse método por padrão só é chamado quando o aplicativo não está em background ou fechado. Ou seja, no método atual, na prática as notificações apenas são agrupadas quando o usuário está com o app aberto. Para permitir que sejam agrupadas a todo momento, mesmo com o app fechado, teremos que refatorar toda esta parte de notificações, provavelmente será necessário também modificar a API, que é a que envia as notificações para os servidores da Google, e o iOS.
