### ISSUE TITLE
Push Notification - Não esta exibindo os ícones nas notificações

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#208]
Parou de exibir os ícones nas notificações. Esta exibindo este quadrado branco agora.
![screenshot_2017-07-12-10-07-15](https://user-images.githubusercontent.com/20990100/28120237-cf0b85a8-66ed-11e7-9f97-b8838caae637.png)
![screenshot_2017-07-12-10-07-35](https://user-images.githubusercontent.com/20990100/28120240-d09f800e-66ed-11e7-9167-a2d9f012ef90.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Ajuste será liberado essa tarde em nova atualização da versão Beta
![img_4597](https://user-images.githubusercontent.com/20994342/28371304-f92c4f9a-6c72-11e7-8f91-1d94298b2134.JPG)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho as primeiras notificações estavam com o ícone, mas quando cheguei no pedido as notificações ficaram sem o ícone e desagrupadas.

![whatsapp image 2017-08-19 at 07 37 56](https://user-images.githubusercontent.com/20990100/29485932-8b93209c-84b1-11e7-829a-69e117036414.jpeg)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Olha como ficou agora.

![screenshot_2017-08-19-11-54-29](https://user-images.githubusercontent.com/20990100/29487868-8452478e-84d6-11e7-87db-e31555b17544.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.0.20. Importante ressaltar que as notificações não estão sendo agrupadas quando o app encontra-se fechado, discorri sobre isso na issue relativa ao assunto, a #207

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já publicado em produção.
