### ISSUE TITLE
Meu Cadastro - Não esta exibindo os dados cadastrados

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#209]
![screenshot_2017-07-12-10-27-48](https://user-images.githubusercontent.com/20990100/28120292-f5c868f0-66ed-11e7-82e2-fa79afa1a38d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A API está fora do ar no momento, estamos fazendo algumas modificações e testando.

**Comment by raphaelMCarvalho** [comment]
Fechando a issue já que se referia a downtime do servidor de testes.
