### ISSUE TITLE
Tela Inicial - Botão Entrar parcialmente oculto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#21]
Depois de digitar o e-mail e senha o botão de entrar ficar parcialmente oculto dificultando a vida do usuário. Podemos subir um pouco o quadro para deixar o botão visivel?
![image](https://cloud.githubusercontent.com/assets/20990100/18618718/9f1ed9f4-7dc2-11e6-9b4d-3d049d72ef81.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo o teclado fica visível porque o input está em algum campo. Como as dimensões variam de dispositivo pra dispositivo, não tem como fazer ajuste "fixo" no layout, mas há outras alternativas. Vamos ajustar aqui pra ficar beleza.
