### ISSUE TITLE
Meus orçamentos - Não esta carregando os orçamentos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#210]
![screenshot_2017-07-12-10-28-36](https://user-images.githubusercontent.com/20990100/28120317-102e98e0-66ee-11e7-9633-545f3c41f9c9.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A API está fora do ar no momento, estamos fazendo algumas modificações e testando.

**Comment by raphaelMCarvalho** [comment]
Fechando a issue já que se referia a downtime do servidor de testes.
