### ISSUE TITLE
Meus Orçamentos - Excluir nome da loja das mensagens

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#211]
Na web nós chegamos a conclusão que não devemos exibir o nome das lojas nas mensagens dos orçamentos. Agora precisamos aplicar este mesmo conceito nos aplicativos excluindo os nomes das lojas.
![img_6622](https://user-images.githubusercontent.com/20990100/28385007-ee06ce2c-6c9c-11e7-88b5-6d42d716bb4a.PNG)
![screenshot_2017-07-19-12-30-08](https://user-images.githubusercontent.com/20990100/28385031-03625228-6c9d-11e7-941f-45d74de90db6.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.0.17 que estará na loja na próxima hora.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível no iOS na versão 2.2.24

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já publicado em produção.
