### ISSUE TITLE
Criar Pedido - No iOS é possível criar um pedido com valor inferior ao pedido mínimo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#212]
No Android o app não deixa o usuário criar um pedido com valor inferior ao pedido mínimo da loja:
![image](https://user-images.githubusercontent.com/20990100/28385126-551bd5f8-6c9d-11e7-86f9-18f2dac749ff.png)

Já no iOS não existe esta trava.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Estará disponível no Testflight daqui a pouco, versão 2.2.23

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já publicado em produção.
