### ISSUE TITLE
Criar Orçamento - Não é possível apagar a observação

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#213]
Ao editar um produto o usuário não consegue apagar uma observação.
![image](https://user-images.githubusercontent.com/20990100/28476507-9e8f1a4e-6e26-11e7-94ea-d54a9ada4c60.png)
![image](https://user-images.githubusercontent.com/20990100/28476516-a46e3ecc-6e26-11e7-9bff-07585c145959.png)
![image](https://user-images.githubusercontent.com/20990100/28476518-a69faa28-6e26-11e7-98ce-74082ec6f076.png)
![image](https://user-images.githubusercontent.com/20990100/28476522-a8574754-6e26-11e7-8184-c4c3608cc6d8.png)

**Comment by raphaelMCarvalho** [comment]
Disponível na versão 2.0.17 que estará disponível na loja na próxima hora.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já publicado em produção.
