### ISSUE TITLE
Tela Tutorial - Acesse

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#214]
Esta muito difícil clicar em "Acesse" nas telas de tutorial.

Temos que aumentar o texto e área para o clique.

![image](https://user-images.githubusercontent.com/20990100/29477230-ef760f26-843d-11e7-9807-4d1e66303c58.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Nos meus testes não percebi dificuldade para tocar no Acesse, mas de qualquer forma, aumentei a distância em relação ao Cadastre-se e aumentei a área tocável. Não é necessário aumentar o tamanho de fonte, até porque essa mudança implica em alterar o layout recebido da Agência para os diversos tamanhos de tela (aumentar a fonte de uma parte implica em aumentar o tamanho de fonte das outras linhas e ajustar todas as margens e espaçamentos novamente).

Disponível na versão Beta 2.0.14

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já publicado em produção.
