### ISSUE TITLE
Formas de pagamento - Alterar a ordem

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#219]
Colocar as formas de pagamento na mesma ordem do cadastro.

![arquivo_005](https://user-images.githubusercontent.com/20990100/29482173-9ff86bfe-8462-11e7-96bd-17ba5c1fe911.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Em qual tela do iOS seria essa captura? No caso do Android, revisamos e vimos que quando o cliente está analisando as respostas de orçamento, as formas de pagamento são ordenadas com base nas mais "em conta", as que tem desconto, menor número de parcelas, etc. Nas outras telas do Android, deixamos na mesma ordem da versão web e vamos subir no Beta.

**Comment by raphaelMCarvalho** [comment]
Android está como planejado, iOS é preciso maiores detalhes conforme mensagem anterior.
