### ISSUE TITLE
Tela após o cadastro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#22]
O usuário deve ser direcionado para a página "criar o orçamento" quando for o primeiro acesso. Não faz sentido exibir a tela de "Meu resumo" vazia.
![image](https://cloud.githubusercontent.com/assets/20990100/18618725/b16d63e6-7dc2-11e6-8c8b-5259cb2c74c5.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo a princípio a tela Meu Resumo logicamente é a primeira tela que o usuário vê, geralmente é assim; seguimos a mesma lógica da web que a NA+ construiu.
