### ISSUE TITLE
Negociação - Mensagem grande

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#221]
É fácil fazer aumentar as linhas da caixa de texto enquanto o usuário digita a mensagem grande?

![arquivo_003](https://user-images.githubusercontent.com/20990100/29482194-485b4cd0-8463-11e7-8c5f-46bd56cd6c00.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Pelo que entendi da descrição da issue, você se refere à caixa de texto, não às linhas que são exibidas. Caso esteja se referindo às linhas exibidas, e não à caixa de texto, essa issue já foi resolvida e fechada.
