### ISSUE TITLE
Negociação - Melhorar ao digitar uma mensagem grande 

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#225]
A caixa de texto deveria aumentar quando o usuário digita uma mensagem grande.

![screenshot_2017-08-19-11-54-01](https://user-images.githubusercontent.com/20990100/29487862-6e6c5180-84d6-11e7-8074-e3c2ea82ccf0.png)

**Comment by lucasretondo** [comment]
Ficou ótimo quando é a primeira, mas quando já existem outras mensagens não é possível o usuário saber o que ele esta digitando.

![whatsapp image 2017-08-21 at 10 58 46](https://user-images.githubusercontent.com/20990100/29522635-39f65424-8660-11e7-85a5-575da1e91fb4.jpeg)

![whatsapp image 2017-08-21 at 10 58 47 1](https://user-images.githubusercontent.com/20990100/29522634-39d85938-8660-11e7-94a8-32b37f779d60.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.0.12
