### ISSUE TITLE
Meus Pedidos - O menu esta sobreposto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#226]
Na tela de informações do Meus Pedidos o menu superior esta com o "Produto" e "Mensagens" sobrepostos.

![arquivo_000](https://user-images.githubusercontent.com/20990100/29522275-0cd8575e-865f-11e7-96a6-9ab47950db51.png)

Nas outras telas isso não ocorre.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho estou testando a versão 2.2.15 e o texto do menu continua sobreposto. Existe uma nova versão?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Tem sim a versão nova, 2.2.16, havia sido enviada pra loja mas não tinha sido liberada no TestFlight, veja agora por favor.

**Comment by raphaelMCarvalho** [comment]
iPhone 5
![simulator screen shot 28 de ago de 2017 10 47 00](https://user-images.githubusercontent.com/20994342/29776182-3e4f59e8-8bde-11e7-9d72-aec60160b546.png)
