### ISSUE TITLE
Push Notification - Esta mandando push a cada nova resposta

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#228]
Os apps ainda estão recebendo os pushs a cada nova resposta.

![arquivo_002](https://user-images.githubusercontent.com/20990100/29522212-d8a58948-865e-11e7-9c14-676d18baf705.png)

![whatsapp image 2017-08-21 at 10 58 48](https://user-images.githubusercontent.com/20990100/29522567-06f855ae-8660-11e7-9249-94664fca3dca.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo As atualizações referentes a push notifications e e-mails ainda não subiram pra API.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ok, é que o Claudinei falou que tinha subido tudo. Vamos aguardar vcs subirem para voltar aos testes então.

@JuliaAlmeida para seu conhecimento.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @JuliaAlmeida Os testes podem continuar livremente, só lembrar que push e e-mails ainda não subiram.
