### ISSUE TITLE
Negociação - Trocar símbolo por "Avançar"

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#229]
Trocar o símbolo do carrinho por "Avançar"

![whatsapp image 2017-08-21 at 10 58 44](https://user-images.githubusercontent.com/20990100/29522677-679fe840-8660-11e7-89e2-d21e0357c770.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.0.12
