### ISSUE TITLE
Meus Pedidos - Não é possível saber qual é o produto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#230]
O usuário não tem como saber a descrição completa do produto. Vamos usar o mesmo padrão do iOS.

![whatsapp image 2017-08-21 at 10 58 50](https://user-images.githubusercontent.com/20990100/29522737-a079c7c6-8660-11e7-9a89-c860f24cc26a.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já publicado em produção.
