### ISSUE TITLE
Meus Orçamentos - Escolher forma de pagamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#231]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Ao escolher a forma de pagamento.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Que não exibisse a mensagem de erro quando o campo estiver selecionado.

## 3. Descrição do que ocorreu

Deu uma mensagem que falta selecionar o cartão, mas aparentemente esta selecionado.

## 4. Captura de tela

![whatsapp image 2017-08-21 at 10 58 41](https://user-images.githubusercontent.com/20990100/29522810-00d50f90-8661-11e7-8e25-dd7fe57e0a30.jpeg)

## 5. Passos para reproduzir a ocorrência

Selecione a opção de pagar com o cartão de crédito, com a bandeira mastercard em 30 dias. Depois escolhi a opção com dinheiro e voltei para o cartão de crédito.

**Comment by raphaelMCarvalho** [comment]
Disponível na versão 2.0.17 que estará disponível na loja na próxima hora.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já publicado em produção.
