### ISSUE TITLE
 Orçamento - Cliente aparentemente não consegue responder dúvida do orçamento

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/customer_mobile_app#232]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)
Orçamento enviado, cliente na aba de mensagens do orçamento para responder dúvida do lojista.
APP-ANDROID ASUS ZENFONE

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Ao clicar no botão de enviar a mensagem demonstrasse que a mensagem foi enviada.
## 3. Descrição do que ocorreu

Cliente abriu o orçamento 986 no celular. Abriu a aba de Mensagens e foi responder a dúvida do lojista. Aparenta que a mensagem não foi enviada. Cliquei em voltar e depois abri novamente o orçamento 986 no celular e na aba de Mensagens estava a mensagem enviada.

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/30830371/29665779-065b1a70-88ac-11e7-94f5-21beb69db312.png)
![image](https://user-images.githubusercontent.com/30830371/29665792-0c99df34-88ac-11e7-8506-c4044eb90c88.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Não conseguimos reproduzir o problema apresentado nas capturas de tela. Você teria como reproduzir e passar pra gente mais detalhes?

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho eu não tinha conseguido reproduzir esse problema nos últimos dias.
Mas hoje não consegui responder a ultima dúvida do orçamento, pois a caixa de digitação abre e fecha muito rápido. Consegui responder as demais 3 mensagens.
![image](https://user-images.githubusercontent.com/30830371/30640627-030d4742-9dda-11e7-92d0-41852b3ac267.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Problema resolvido, estará disponível na versão 2.0.26 que foi enviada agora para a Google Play e está neste momento sendo processada.
