### ISSUE TITLE
Meus Orçamentos - Excluir botão Arquivar

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#233]
Excluir o botão "Arquivar". Os usuários estão clicando no botão por engano.

![image](https://user-images.githubusercontent.com/20990100/29717054-25928436-8984-11e7-8ac2-faf570d81eea.png)

**Comment by raphaelMCarvalho** [comment]
Disponível na versão Beta 2.0.14

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já publicado em produção.
