### ISSUE TITLE
Notificação - Só recebo quando estou mexendo no APP

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/customer_mobile_app#234]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Em todas as etapas que  o cliente deveria receber uma notificação no celular.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Só recebi notificações enquanto usava o APP, depois de 5 minutos sem abrir  a janela do APP no celular eu já não recebia mais as notificações. (Não fechava o APP, só deixava de mexer nele)
Como também teve 1 notificação que recebi com o símbolo do Praconstruir e as outras com um quadrado branco.
No meu celular (Asus zenfone Selfie) as notificações do APP estão ativas como para o facebook, instagram e email.

## 3. Captura de tela de como está hoje

![image](https://user-images.githubusercontent.com/30830371/29778294-42f01efe-8be5-11e7-8860-481e7fe80159.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Isso está relacionado ao Zenfone, particularmente ao Auto Start Manager. Pesquisando vi que há muitos relatos desse comportamento, e aparentemente pra que as push notifications sejam recebidas pelo nosso app é necessário uma ação do usuário no Auto Start Manager. Não há nesse momento o que fazer no aplicativo pra evitar esse comportamento, em outros dispositivos Android que testamos está funcionando adequadamente.

**Comment by raphaelMCarvalho** [comment]
https://www.asus.com/support/FAQ/1013752/

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho entendi. E sobre o símbolo das notificações?

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida A questão do ícone vamos resolver na issue #208
