### ISSUE TITLE
Frete - Exibir o valor do pedido

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#236]
Vamos padronizar e exibir o valor do pedido no rodapé desta tela do Android, neste exemplo R$ 774,99

![image](https://user-images.githubusercontent.com/20990100/30344362-6cdf37d8-97d7-11e7-9f71-d66ec422109d.png)

Detalhes do valor:

![image](https://user-images.githubusercontent.com/20990100/30344395-89c46b66-97d7-11e7-8b1b-997b10faf5d7.png)

**Comment by raphaelMCarvalho** [comment]
Disponível na versão 2.0.17 que estará disponível na loja na próxima hora.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já publicado em produção.
