### ISSUE TITLE
Notificação - Não estou recebendo notificação de nova dúvida no orçamento no APP

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/customer_mobile_app#238]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Lojistas enviando novas dúvidas no orçamento.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Usuário novo (cliente) receber no APP-Android as notificações de novas dúvidas no orçamento (nova mensagem).

**Comment by JuliaAlmeida** [comment]
Também não recebo no APP notificações de nova mensagens na Negociação.
Mas recebo no email. (cli18@mailinator.com)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida , por favor teste na nova versão Beta que estará disponível dentro de 1 hora. A princípio se estiver tudo OK com o usuário, ele recebe sim as notificações de mensagem no orçamento, conforme captura de tela.

![screenshot_20171017-120827](https://user-images.githubusercontent.com/20994342/31670374-ceccc5a2-b32d-11e7-8770-19fbbd1bb3be.png)

**Comment by raphaelMCarvalho** [comment]
A mesma coisa para Pedido. Não cheguei a testar antes dos ajustes que fiz relativos a outras issues, mas não estaria este problema que enfrentas relacionado ao teu aparelho, como na issue fechada #234 ?

![screenshot_20171017-122805](https://user-images.githubusercontent.com/20994342/31670955-339ce20e-b32f-11e7-97a5-68d383cf6ade.png)

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho eu estou com um problema que não sei como seguir: no meu celular o app não reconhece nenhum dos emails que eu normalmente utilizo para os testes de cliente.
Ate "recadastrei" o cli5@mailinator.com no celular, mandei 1 orçamento que nenhuma loja recebeu. E quando abri esse cli5 no computador ele aparece como cadastro antigo dele dos meus testes.
Abri o playstore e não tem opção de atualizar o App, o que faço?

**Comment by raphaelMCarvalho** [comment]
Bom dia Julia, verifique se você está com a versão Beta do app Android ou a versão de produção. Pelo seu relato, acredito que no app você esteja utilizando o ambiente de produção (https://praconstruir.com.br <http://praconstruir.com.br/>) e no navegador esteja utilizando o ambiente de homologação (https://pdcc.angularlabs.com.br). Você pode confirmar fazendo login na produção com o usuário e senha que você esperava ter cadastrado na homologação, caso obtenha sucesso, então foi isso mesmo que ocorreu.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho  como verifico qual é a versão do meu app?  Só consigo ver que é e versão 2.0.20  
Eu desinstalei e abri o link que vocês me mandaram a tempos para eu baixar a versão teste pelo playstore e mesmo assim da problema com os emails.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Você está com a versão de produção, logo, está solicitando orçamentos em https://praconstruir.com.br .

![screen shot 2017-10-18 at 11 56 18](https://user-images.githubusercontent.com/20994342/31722690-230fde5e-b3f3-11e7-85e1-09bcfe0469f9.png)

O que ocorre e acabei não explicando, é que o ciclo é sempre: app em Beta para homologação, e após aprovado, este app é **movido** do Beta para produção. Dessa forma, sempre após o lançamento em produção, não há um Beta conectado à homologação, ontem quando entrei em contato para realização de testes havia. Mais tarde envio uma nova versão para o Beta, com o mesmo status da produção, só que apontando para a homologação.
