### ISSUE TITLE
Criar negociação - Melhorar comunicação

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#241]
Vamos substituir o termo "Negociar" por "Avançar" nesta tela:
![image](https://user-images.githubusercontent.com/20990100/32994793-70f7f77c-cd53-11e7-8c84-37a4107dc643.png)

Mudar a mensagem para "Você deseja iniciar a negociação direto com as lojas sem compromisso?"
![image](https://user-images.githubusercontent.com/20990100/32994823-858bc916-cd53-11e7-8f3e-df31b569cbeb.png)

Mudar mensagem para "Negociações iniciadas, aguarde o contato da loja ou envie uma mensagem"
![image](https://user-images.githubusercontent.com/20990100/32994857-9ea73df4-cd53-11e7-9204-3604c595fa96.png)
É possível aumentar a fonte do número da negociação e nome da loja?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho a mensagem ficou certa, mas achei a fonte pequena. É possível aumentar um pouco?

Esta issue não impede o deploy, pode subir como esta.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho e @claudineicaetano o que vocês acham da proposta abaixo?

![image](https://user-images.githubusercontent.com/20990100/33127190-9f2a4bd2-cf6e-11e7-92ca-d7dda16237d3.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A fonte desse dialog não está pequena, acredito que seja uma configuração do seu dispositivo, percebi que a fonte sendo exibida no seu celular é alguma customização, é Samsung? Veja o caso de um dispositivo com configuração padrão, antes estava grande a fonte, depois da mudança de ontem ficou maior ainda:

![screenshot nov 22 2017 1_19_16 pm](https://user-images.githubusercontent.com/20994342/33134963-4528be42-cf88-11e7-82ab-2cccc559db56.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Provavelmente sua configuração está mantendo as fontes de dialog com tamanho pré-definido, dando override nas nossas mudanças. Sugiro alterar essa configuração ou testar em outro dispositivo.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho eu uso um Moto E antigão. Mas o que você achou a minha proposta de colocar um título e depois a explicação?
