### ISSUE TITLE
Mudar tela de comparação de preços

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#242]
Atualmente quando o usuário cai na tela de cotações abaixo:
![image](https://user-images.githubusercontent.com/20990100/33072569-2f7c92bc-cea7-11e7-823e-17ac9cf1c2ff.png)
depois tem que avançar para selecionar o pagamento neste tela:
![image](https://user-images.githubusercontent.com/20990100/33072598-51fe8cdc-cea7-11e7-80a5-c56261013f75.png)

A proposta é simplificar apresentando no primeiro acesso a tela de resumo com o otimizador de menor custo já selecionado. Seria algo assim:
![image](https://user-images.githubusercontent.com/20990100/33072637-7e7296d2-cea7-11e7-9e4f-c646505ac357.png)

Neste tela o usuário terá as opções de avançar e ir para a tela abaixo:
![image](https://user-images.githubusercontent.com/20990100/33072667-95473930-cea7-11e7-9dfe-dc991b83182e.png)

Ou clicar em selecionar otimizadores. Neste caso devemos exibir os otimizadores com os valores conforme abaixo:
![image](https://user-images.githubusercontent.com/20990100/33072709-b1d98026-cea7-11e7-8d22-f4576861e4d2.png)

Se ele selecionar um otimizar volta para a tela de resumo acima.

Se ele clicar em personalizar ele é direcionado para a tela abaixo:
![image](https://user-images.githubusercontent.com/20990100/33072745-cf302b66-cea7-11e7-9208-c8c7d3c7ce71.png)
onde pode selecionar as lojas:
![image](https://user-images.githubusercontent.com/20990100/33072761-d9922168-cea7-11e7-902f-b7a3d8617aba.png)
e depois que clicar em avançar voltaria para a tela resumo anterior.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não consegui compreender essas modificações, nem a dimensão e complexidade delas, vai ser preciso explicar pro @claudineicaetano e partirmos daí. Talvez fosse bom trabalhar uma proposta de layout pra uma lista com 20 produtos ao invés de 2, por exemplo, e ver a viabilidade da experiência do usuário.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho discuti isso com ele hj. Combinei de abrir as issues para vocês avaliaram, acho que não deu tempo dele fazer com você. Sorry.
