### ISSUE TITLE
Corrigir a tela de selecionar lojas

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#243]
Hoje a tela para o usuário mudar a loja esta assim:
![image](https://user-images.githubusercontent.com/20990100/33072927-6bb1ebb4-cea8-11e7-8105-7093a79bc29c.png)

Temos que mudar o título do menu, excluir a medida e dar a opção do usuário não selecionar nenhum produto.
![image](https://user-images.githubusercontent.com/20990100/33073008-a5af7660-cea8-11e7-9a36-c7ba3c0cd580.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Nessa tela efetivamente o usuário está selecionando um produto de uma loja, não selecionando uma loja, não seria uma correção na verdade, é uma alteração que semanticamente é incorreta, mas podemos fazer.

Para permitir que o usuário não selecione um produto não basta colocar um botão aí, é preciso repensar todo o fluxo, especialmente na tela anterior. É preciso discutir as telas para se chegar a algo, no momento não há o que ser feito nessa tela, ela depende de outras definições, vamos aguardar. Por exemplo: o que ocorre com os produtos não selecionados? Onde e como são exibidos? É possível ao usuário fazer algo em relação a eles no celular? É possível ele mudar de ideia uma vez que não selecionou nenhum?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho eu entendo que nesta tela ele esta selecionando um fornecedor, dado que ele clicou sobre o "TROCAR LOJA" do produto. Sobre não escolher o produto vamos deixar para uma nova issue.
