### ISSUE TITLE
Eliminar os ícones e colocar a qtd e medida em outra linha

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#244]
Acho que os ícones não estão agregando valor, só estão só ocupando espaço:
![image](https://user-images.githubusercontent.com/20990100/33073162-2235f6fa-cea9-11e7-9b43-7156900dc0d1.png)

E mais, somente na tela de pedido nós colocamos a descrição produto em uma linha, e a qtd x medida em outra. Nas demais telas temos espaço mas deixamos tudo apertado:
![image](https://user-images.githubusercontent.com/20990100/33073168-27a130be-cea9-11e7-999d-699389fe7061.png)

Por isso a minha proposta é excluir os ícones de deixar sempre a "qtd x medidas" abaixo da descrição do produto:
![image](https://user-images.githubusercontent.com/20990100/33073203-447daec4-cea9-11e7-8776-ce94e333e3b2.png)

![image](https://user-images.githubusercontent.com/20990100/33073239-67093440-cea9-11e7-9b51-4e6e3f982c19.png)

![image](https://user-images.githubusercontent.com/20990100/33073256-772ab100-cea9-11e7-8626-653f94fbc6b2.png)

![image](https://user-images.githubusercontent.com/20990100/33073272-851a276e-cea9-11e7-8e6e-1c71220227d8.png)

![image](https://user-images.githubusercontent.com/20990100/33073279-8c978874-cea9-11e7-8a17-5f1f3f59f378.png)

![image](https://user-images.githubusercontent.com/20990100/33073292-9913ee4e-cea9-11e7-84aa-317a13849558.png)

![image](https://user-images.githubusercontent.com/20990100/33073303-a47a587c-cea9-11e7-84d1-efe8545e7bcc.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Os ícones são parte importante do layout e existem por todo o aplicativo. Removê-los apenas de uma parte do app fará com que o layout não seja mais homogêneo, vai ser uma quebra na experiência pro usuário. Ou se remove do aplicativo inteiro, repensando todo o layout, ou se mantém os ícones e fazemos outras modificações. É possível remover apenas destas telas especificadas, mas é um erro crasso de UX.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho a ideia é remover de todo o app, se esqueci alguma tela foi falha minha.
