### ISSUE TITLE
Simplificar criação de orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#245]
Podemos simplificar ainda mais o fluxo de criação do orçamentos apenas alterando os títulos, nomes dos botões e excluindo algumas partes:

![image](https://user-images.githubusercontent.com/20990100/33073401-f8323a5c-cea9-11e7-9f41-6e1bad70a92a.png)

![image](https://user-images.githubusercontent.com/20990100/33073408-fc8210e6-cea9-11e7-8cd6-c2568a464509.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O termo "Lista de compras" não é usado no Pra Construir, sempre adotou-se a ideia de uma lista de produtos pra solicitação de orçamento, já que a princípio esse termo denota que haverá uma compra na plataforma, o que de fato não ocorre. No início do projeto houve essa discussão e foi decidido não utilizá-lo.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho bem lembrado, vamos colocar lista de produtos.

**Comment by lucasretondo** [comment]
Vamos seguir com a proposta de vocês.
