### ISSUE TITLE
Novo fluxo de comparação de preço - Está travando

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#248]
Quando tento ver as respostas de um orçamento com um usuário novo o app trava. Quando eu uso um usuário já cadastrado dá certo.

Fiz os testes com os usuários cl1@mailinator.com (cli1$$) e cl2@mailinator.com (cli2$$).

![whatsapp image 2017-12-29 at 09 15 46](https://user-images.githubusercontent.com/20990100/34436077-8958628a-ec79-11e7-824d-ca7e879effb2.jpeg)

![whatsapp image 2017-12-29 at 09 15 46 1](https://user-images.githubusercontent.com/20990100/34436081-8e28fafe-ec79-11e7-910f-f8ab65065f59.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não faltou algum passo na descrição da situação que você enfrentou? Pois fiz login com os dois usuários, visualizei todos os orçamentos que existiam, customizei e gerei os pedidos sem problema, limpei a lista.

![screenshot_1514553334](https://user-images.githubusercontent.com/20994342/34437911-cb3250a2-ec89-11e7-8358-041db96b748a.png)

![screenshot_1514553153](https://user-images.githubusercontent.com/20994342/34437916-d5d4fbe0-ec89-11e7-9bb4-6f339c1fac37.png)

![screenshot_1514553272](https://user-images.githubusercontent.com/20994342/34437946-efc831f2-ec89-11e7-9678-5ae4e4ec8a38.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o problema ocorre quando o status é aguardando resposta. Na verdade neste status não deveria ter a opção de ver respostas, concorda?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Concordo, realmente estava faltando esse passo na descrição da issue pra que pudéssemos reproduzir o problema. Vamos verificar.
