### ISSUE TITLE
Criar Orçamento - Preencher automaticamente quando tiver só uma medida

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#249]
Acho que já tinha esta regra de preencher o campo medida automaticamente quando tiver somente uma medida.

![whatsapp image 2017-12-29 at 09 15 45](https://user-images.githubusercontent.com/20990100/34436105-b8d6f44a-ec79-11e7-985d-b6f494ee454b.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.7 que estará na loja daqui a pouco.
