### ISSUE TITLE
Menu - Ordenar igual ao site

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#25]
Precisamos mudar a ordem dos itens no menu lateral para ficar igual ao site.
![screenshot_2016-12-14-11-27-23](https://cloud.githubusercontent.com/assets/20990100/21191113/43f22a44-c20b-11e6-8097-244129d0edc6.png)
![image](https://cloud.githubusercontent.com/assets/20990100/21191138/5832705e-c20b-11e6-9b17-a6fbe2b0d323.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido
