### ISSUE TITLE
Árvore de produtos - Não esta abrindo os itens da madeira

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#250]
Não esta abrindo os itens da categoria "Madeira".

![whatsapp image 2017-12-29 at 09 15 48](https://user-images.githubusercontent.com/20990100/34436135-e1d7c6da-ec79-11e7-87ac-a98b3150dd8a.jpeg)

![whatsapp image 2017-12-29 at 09 15 47](https://user-images.githubusercontent.com/20990100/34436138-e5c5524e-ec79-11e7-9a20-79d36d83f07e.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Na web também não abre, não é uma issue do Android. Vamos verificar a API e a base de dados, para ver se há produtos registrados para a categoria na árvore.
