### ISSUE TITLE
Meu Resumo - Mudar de "Pra Construir" para "Meu Resumo"

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#251]
Tela meu resumo:

![screenshot_2017-11-17-19-47-33](https://user-images.githubusercontent.com/20990100/34471533-6611c2c8-ef33-11e7-9663-c3b4dec29d5c.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.10
