### ISSUE TITLE
Novo fluxo de comparação - Checar soma do frete no total

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#252]
Quando eu abro os detalhes da cotação da "Sua loja" veja que não é cobrado frete:
![image](https://user-images.githubusercontent.com/20990100/34529109-1a5e922e-f092-11e7-941d-d17d8671a359.png)

Depois quando eu abro a cotação da "Loja 3" tem R$ 250 de frete;
![image](https://user-images.githubusercontent.com/20990100/34529134-2dfa37b6-f092-11e7-8d5e-e96c82c23c75.png)

E quando eu volto para a "Sua loja" o frete de R$ 250 é exibido, mas não entra na soma:
![image](https://user-images.githubusercontent.com/20990100/34529152-3d36d45a-f092-11e7-811b-8386d7c71d97.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.8 que logo estará na loja
