### ISSUE TITLE
Otimizador - Mudar o nome do otimizador para menos fornecedores

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#253]
O que vocês acham de mudarmos o nome do otimizador "Menor quantidade de fornecedores" para "Menos fornecedores"?

![image](https://user-images.githubusercontent.com/20990100/34529234-6fe76018-f092-11e7-951b-a343a52c4ecc.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.10
