### ISSUE TITLE
Otimizador - exibir o valor total junto ao nome da otimização

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#254]
Vamos voltar a exibir ao lado o nome do otimizador o valor. Não sei pq tiramos isso.

![image](https://user-images.githubusercontent.com/20990100/34529373-d09895da-f092-11e7-8a49-cef8cb2f2538.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.11
