### ISSUE TITLE
Novo fluxo de comparação - Exibir o valor líquido total no rodapé da aba Recomendado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#255]
Vamos incluir na tela dos valores otimizados o valor total no rodapé.

No exemplo abaixo o valor exibido é de R$ 750, quando avança vê que é R$ 675 com o desconto.

Por isso acho melhor incluir na tela do otimizador o valor total de R$ 675 e um seta com os valores detalhados.

![image](https://user-images.githubusercontent.com/20990100/34530324-f00a9cda-f095-11e7-8f00-c998d76b13f8.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.8 que logo estará na loja
