### ISSUE TITLE
Menu lateral: não exibir fontes em cor laranja

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#256]
Vamos padronizar para o menu lateral sempre exibir o criar orçamento em cinza.

Em algumas telas ele fica laranja.

![image](https://user-images.githubusercontent.com/20990100/34530586-c6c84948-f096-11e7-9fc6-371f08bb4550.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.10
