### ISSUE TITLE
Mensagem de negociação iniciada: adicionar quebra de linha entre itens

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#257]
Vamos colocar um espaço pequeno entre as negociações iniciadas.

![image](https://user-images.githubusercontent.com/20990100/34530645-f6b3c204-f096-11e7-8311-68b835c854a0.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.11
