### ISSUE TITLE
Criar Orçamento - Não é possível ver a qtd do último item

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#258]
Não é possível ver a quantidade do último item da lista de materiais pq ele esta atrás do botão de adicionar mais itens.

![whatsapp image 2018-01-03 at 17 43 58](https://user-images.githubusercontent.com/20990100/34536921-e5d7bb86-f0ad-11e7-858b-154274e1f580.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.10
