### ISSUE TITLE
Árvore de materiais - Não exibir produtos quando tiver só um item

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#259]
Precisamos criar a mesma regra da web no android para não exibir a lista de materiais quando tiver somente um item para escolher.

![whatsapp image 2018-01-03 at 17 43 58 1](https://user-images.githubusercontent.com/20990100/34536975-136831e8-f0ae-11e7-86b2-59dd52f50ba2.jpeg)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Disponível na versão 2.1.0.11
