### ISSUE TITLE
Meu Resumo - Filtrar os status exibidos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#26]
Temos que usar o mesmo critério do site para filtrar os status exibidos no Meu Resumo, hoje estamos exibindo erroneamente o status "aguardando confirmação fornecedor" por exemplo.
![screenshot_2016-12-14-11-29-14](https://cloud.githubusercontent.com/assets/20990100/21191207/8b5ec9c8-c20b-11e6-8282-176fffee4c36.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido

**Comment by lucasretondo** [comment]
O Meu Ressumo do Android esta diferente da web

Android:
![screenshot_20170111-100832](https://cloud.githubusercontent.com/assets/20990100/21848213/e37c85f0-d7e6-11e6-8ec8-b531bd03a0c6.png)

Web:
![image](https://cloud.githubusercontent.com/assets/20990100/21848238/f552f570-d7e6-11e6-91cf-b193b7b334ec.png)
