### ISSUE TITLE
Meus Pedidos - Por que a data de entrega é vermelha

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#27]
A data de entrega de alguns pedidos finalizados esta vermelha, pq?
![screenshot_2016-12-14-11-29-38](https://cloud.githubusercontent.com/assets/20990100/21191281/c2fb4b22-c20b-11e6-9327-cbed0ede57c9.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido
