### ISSUE TITLE
Criar Orçamento - Mensagem desnecessária

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#29]
O usuário consegue fazer uma lista de compra não logado, mas não consegue solicitar o orçamento, até aqui perfeito.

Porém hoje ele faz a lista de compras não logado, escolhe a forma de pagamento e recebe a mensagem abaixo ao solicitar o orçamento:
![screenshot_2016-12-14-11-34-29](https://cloud.githubusercontent.com/assets/20990100/21191720/3c79a0d8-c20d-11e6-9099-27e3e641f451.png)

Esta mensagem não ajuda o cliente em nada na minha opinião.

Nesta situação, devemos direcionar o cliente para a tela de login abaixo onde ele pode fazer o login ou se cadastrar.
![screenshot_2016-12-14-14-57-26](https://cloud.githubusercontent.com/assets/20990100/21191929/e92eff4e-c20d-11e6-9d04-f37d9044e850.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido
