### ISSUE TITLE
Melhorar o Auto complete

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#31]
É possível usar a mesma api do Elastic da web no android?
![screenshot_2016-12-14-22-30-13](https://cloud.githubusercontent.com/assets/20990100/21207168/b5f9b39a-c24d-11e6-8762-a76cce2e1c0f.png)
![screenshot_2016-12-14-22-30-07](https://cloud.githubusercontent.com/assets/20990100/21207177/c43aceda-c24d-11e6-8913-e200ee6a33c6.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido. Por favor crie a label 'Para validar' para que eu possa utilizá-la.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido
