### ISSUE TITLE
Não é possível reenviar o orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#32]
Não é possível reenviar um orçamento com status "reenviar"
![screenshot_2016-12-14-17-54-52](https://cloud.githubusercontent.com/assets/20990100/21207216/00270120-c24e-11e6-97b1-f51a3fb9cefb.png)

No status "reenviar" o app deveria seguir o mesmo layout do orçamento com status "salvo"

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido
