### ISSUE TITLE
Dispositivo na horizontal

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#43]
É possível não permitir a rotação?

É impossível usar o app com o celular na horizontal.

![screenshot_20161222-203906](https://cloud.githubusercontent.com/assets/20990100/21444078/1fbb7fae-c891-11e6-872f-679623ec3985.png)

**Comment by lucasretondo** [comment]
Não esta travado para todas as telas:
![screenshot_20170111-101138](https://cloud.githubusercontent.com/assets/20990100/21848446/e89f38f6-d7e7-11e6-9501-a1725badc255.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Foram fixadas apenas as telas onde a experiência de uso ficaria dificultada na horizontal.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho inteligente, você pode me passar quais telas foram bloqueadas para eu incluir no meu plano de testes?
