### ISSUE TITLE
Meus Pedidos - Permite cancelar um pedido no app e não no web

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#51]
No Android o usuário pode cancelar um pedido atrasado com status "Aguardando confirmação", já no site não é possível. Temos que padronizar. O que é mais fácil, adequar o site ou o app?

Android:
![screenshot_20170111-101001](https://cloud.githubusercontent.com/assets/20990100/21848280/276fb066-d7e7-11e6-9c30-94a359d905a2.png)

Web:
![image](https://cloud.githubusercontent.com/assets/20990100/21848334/63a52a16-d7e7-11e6-9e4d-57c6015a2944.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vocês já avaliaram qual é a melhor solução? Vamos conversar antes de vocês implementarem esta mudança.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A solução ideal é aplicar as mesmas regras da web, que já se encontram homologadas e testadas. Estará disponível a atualização na nova versão do Beta.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho blz, manda bala, obrigado.
