### ISSUE TITLE
Menu Superior - Centralizar título da sessão

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#57]
Acompanhei a primeira utilização de algumas pessoas nas últimas semanas e muitas confundiram o a seta de voltar com "Criar Orçamento". É possível centralizar os títulos das sessões para diminuir este tipo de confusão.

Atual
![screenshot_20170227-140408](https://cloud.githubusercontent.com/assets/20990100/24018507/e9f03f94-0a72-11e7-8908-cc1edb4b44cc.png)

Proposto
![screenshot_20170227-140408 v2](https://cloud.githubusercontent.com/assets/20990100/24018512/f0698e0c-0a72-11e7-9e4d-c82afa49ffbb.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Minha sugestão é alterar o título, não centralizá-lo. Digo isso porque entendo que não é a posição que está confundindo os usuários, mas sim a frase, que por estar no infinitivo indica uma ação, exatamente no mesmo tempo que o verbo 'Continuar'. Outro problema que iríamos gerar ao centralizar é que a frase ficaria 'grudada' com o Continuar, em telas menores fica complicado. 

Por exemplo, se ao invés de "Criar orçamento" a gente usasse "Orçamentos", evitaria a confusão.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @claudineicaetano Um exemplo pra fomentar a decisão

![device-2017-03-20-220239](https://cloud.githubusercontent.com/assets/20994342/24128179/ff556352-0db8-11e7-8cf7-74f0ed9ee413.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho gostei, vamos fazer isso. Quais outras telas nós podemos melhor os termos?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo De criar e editar Obra, e de editar orçamento foi o que eu vi. Fiz as modificações e vou subir no Beta pra você avaliar. Se tiver alguma outra tela que achar que pode gerar confusão dá um toque.

**Comment by raphaelMCarvalho** [comment]
Disponível nessa versão:

![screenshot_20170323_204953](https://cloud.githubusercontent.com/assets/20994342/24274899/6448acd0-100a-11e7-97e9-02be0b685969.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho show de bola, obrigado.
