### ISSUE TITLE
Criar Orçamento - Não permite que o usuário selecione mais de 200 unidades

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#59]
Em algumas casos as quantidades são grandes, por exemplo tijolo e bloco.

Por isso não faz sentido limitar em 200 e a forma de rolar tb é muito ruim, temos que pensar em outro formato para este campo.

![img_0693](https://cloud.githubusercontent.com/assets/20990100/25366113/e45383e4-2943-11e7-9f54-7957ce19c1a6.PNG)
![img_0694](https://cloud.githubusercontent.com/assets/20990100/25366117/e8f08460-2943-11e7-82bb-dde8ccaf2628.PNG)

**Comment by lucasretondo** [comment]
É muito ruim ficar rolando para selecionar 2000 tijolos, temos que mudar o tipo de campo para o usuário digitar um número inteiro...

**Comment by claudineicaetano** [comment]
Foi implementado o Picker com dois passos: 1 a 1 até 100 e a partir de 100 de 100 em 100
