### ISSUE TITLE
Criar Orçamento - Trocar tipo de campo do período

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#71]
Não é melhor colocar para o usuário escolher o período com o um combo box ao invés do check box como esta hoje?
![img_0701](https://cloud.githubusercontent.com/assets/20990100/25383399/548f5964-2992-11e7-84d0-710e8f64ef36.PNG)

**Comment by claudineicaetano** [comment]
Será usado o componete padrão do iOS, o switch
