### ISSUE TITLE
Menu superior - Os botões do menu superior são pequenos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#76]
Hoje os botões de voltar e avançar do menu superior são muito pequeno e dificultam a vida de usuário:
![arquivo_000](https://cloud.githubusercontent.com/assets/20990100/25434217/da380e6a-2a61-11e7-8647-dbe8136232ff.png)

O que você acham de mudarmos para:
![image](https://cloud.githubusercontent.com/assets/20990100/25434230/e3a08f9a-2a61-11e7-9249-e2d8dd2967e0.png)

Acho que esta mesma abordagem pode ser usada no Android.

**Comment by claudineicaetano** [comment]
Validar apenas iOS
