### ISSUE TITLE
Cadastro - Mudar o campo Sexo para combo box

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#80]
Não é melhor exibir o campo Sexo como combo box ou invés de check box?

![image](https://cloud.githubusercontent.com/assets/20990100/25464575/873d8362-2ad3-11e7-8107-e2c5c301b462.png)

**Comment by claudineicaetano** [comment]
Será usado o componete padrão do iOS, o switch
