### ISSUE TITLE
Cadastro - Ir para a tela criar orçamento após finalizar o cadastro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#82]
Depois de finalizar o cadastro o usuário volta para a tela do Termo de Uso. Não seria melhor ele ir para a tela Meu Resumo?

![image](https://cloud.githubusercontent.com/assets/20990100/25464645/e7106ff2-2ad3-11e7-83a9-6b46b1ac3719.png)

**Comment by claudineicaetano** [comment]
Validar apenas iOS
