### ISSUE TITLE
Minhas Obras - Mudar Sequencia do cadastro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#84]
A sequencia atual do cadastro de obras:
Tipo da Obra > Tipo imóvel > Responsável > Área e quartos
![image](https://cloud.githubusercontent.com/assets/20990100/25465433/8c36c900-2ad8-11e7-84dd-f6ed21e1cdc8.png)
Esta ruim. Vamos excluir o campo Tipo de Telefone (no Android e web também) e mudar a sequencia para:
Tipo da Obra > Responsável  > Tipo imóvel > Área e quartos
![image](https://cloud.githubusercontent.com/assets/20990100/25465465/ce37c1d8-2ad8-11e7-8ee4-f26b25027f75.png)

**Comment by claudineicaetano** [comment]
Validar iOS

**Comment by lucasretondo** [comment]
Não excluiu do "Tipo de Telefone"

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Validar no Beta Android, versão 1.1.13.
Desde a versão 1.1.12 também estão disponíveis as bandeiras de cartão de débito e crédito.

![captura de tela de 2017-05-21 10-18-30](https://cloud.githubusercontent.com/assets/20994342/26284349/14c23afe-3e0f-11e7-9fe5-ff0d6e13550d.png)
