### ISSUE TITLE
Minhas Obras - Mudar formato campo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#85]
Não ficaria melhor se os campos Tipo de Obra, Imóvel e Telefone fossem em combo box?
![image](https://cloud.githubusercontent.com/assets/20990100/25465433/8c36c900-2ad8-11e7-84dd-f6ed21e1cdc8.png)

**Comment by claudineicaetano** [comment]
Será usado o componete padrão do iOS, o switch
