### ISSUE TITLE
Minhas Obras - Não é possível excluir obra

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#88]
Não achei o botão para excluir a obra:
![image](https://cloud.githubusercontent.com/assets/20990100/25465859/510d7808-2adb-11e7-8c32-f5d10e74bcc2.png)

**Comment by lucasretondo** [comment]
Ele exclui a obra, mas fica preso na mesma tela, assim o usuário não tem como saber se foi excluído.
![img_1712](https://cloud.githubusercontent.com/assets/20990100/26529145/33475b4e-4391-11e7-9bf0-526cbd3d0111.PNG)

Depois de sair e voltar a Minhas Obras
![img_1713](https://cloud.githubusercontent.com/assets/20990100/26529148/3ea77636-4391-11e7-93b5-b3523c5fca76.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A ser disponibilizado em atualização no TestFlight ainda hoje
