### ISSUE TITLE
Notificações em excesso

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/customer_mobile_app#9]
O nosso app gera muitas notificações, precisamos unificar todas as notificações em um único banner igual ao whatsapp
![screenshot_2016-09-17-15-49-33](https://cloud.githubusercontent.com/assets/20990100/18618111/f3c18bc6-7db5-11e6-81f7-b5c7eb28fa95.png)

**Comment by lucasretondo** [comment]
Temos que consolidar as notificações igual ao whatsapp
![screenshot_2016-12-14-16-19-51](https://cloud.githubusercontent.com/assets/20990100/21207250/45a68a54-c24e-11e6-99e7-cf5501547f48.png)
![screenshot_2016-12-14-15-12-28](https://cloud.githubusercontent.com/assets/20990100/21207253/4d564e4c-c24e-11e6-89ea-f23b0bfd3a2e.png)

**Comment by lucasretondo** [comment]
Incluir a notificação no icone (exemplo Facebook):
![screenshot_20170107-221521](https://cloud.githubusercontent.com/assets/20990100/21848468/0b3bc0be-d7e8-11e6-928e-d887477fd696.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Agrupamos as notificações por orçamento/pedido na nova atualização

**Comment by lucasretondo** [comment]
@claudineicaetano não esta chegando mais nenhum notificação. Acabei de fazer um teste com o cli1.

**Comment by lucasretondo** [comment]
Curiosidade, na produção as notificações voltaram, mas sem agrupar.
